zhmach/apps/blogs/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from django.views.generic import RedirectView

from zhmach.apps.blogs.views.blog import (
    BlogCreateView,
    BlogDeleteView,
    BlogDetailView,
    BlogListView,
    BlogUpdateView,
)

app_name = 'blogs'

urlpatterns = [
    path('', RedirectView.as_view(url='blogs/')),
    path('blogs/', BlogListView.as_view(), name='blog-list'),
    path('blogs/add/', login_required(BlogCreateView.as_view()), name='blog-create'),
    path('blogs/<int:pk>/', BlogDetailView.as_view(), name='blog-detail'),
    path('blogs/<int:pk>/update/', login_required(BlogUpdateView.as_view()), name='blog-update'),
    path('blogs/<int:pk>/delete/', login_required(BlogDeleteView.as_view()), name='blog-delete'),
]

zhmach/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LogoutView
from django.urls import path, include
from django.views.generic import RedirectView

from zhmach.apps.accounts.views.login import LoginView

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),

    path('', RedirectView.as_view(url='blogs/')),
    path('blogs/', include('zhmach.apps.blogs.urls', namespace='blogs')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

zhmach/apps/blogs/models/blog.py
from django.conf import settings
from django.db import models
from django.db.models import F
from django.urls import reverse


class Blog(models.Model):
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        verbose_name='Автор',
    )

    created_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата и время создания',
    )
    name = models.CharField(
        max_length=500,
        verbose_name='Наименование',
    )
    image = models.ImageField(
        upload_to='%Y/%m/%d/',
        blank=True,
        null=True,
        verbose_name='Изображение',
    )
    text = models.TextField(
        verbose_name='Текст',
    )
    views = models.PositiveIntegerField(
        default=0,
        verbose_name='Количество просмотров',
    )

    class Meta:
        ordering = ['-created_at']

    def __str__(self) -> str:
        return str(self.name)

    def get_absolute_url(self):
        return reverse('blogs:blog-detail', kwargs={'pk': self.pk})

    def get_update_url(self):
        return reverse('blogs:blog-update', kwargs={'pk': self.pk})

    def get_delete_url(self):
        return reverse('blogs:blog-delete', kwargs={'pk': self.pk})

    def increment_views(self):
        self.views = F('views') + 1
        self.save()

zhmach/apps/accounts/forms/authentication.py
from django.contrib.auth.forms import (
    AuthenticationForm as DjangoAuthenticationForm,
)


class AuthenticationForm(DjangoAuthenticationForm):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)

        self.tune_fields()

    def tune_fields(self):
        self.tune_username_field()
        self.tune_password_field()

    def tune_username_field(self):
        self.fields['username'].widget.attrs.update({'class': 'input'})

    def tune_password_field(self):
        self.fields['password'].widget.attrs.update({'class': 'input'})

zhmach/apps/blogs/forms/blog.py
from django import forms
from django.apps import apps


class BlogForm(forms.ModelForm):
    class Meta:
        model = apps.get_model('blogs.Blog')
        fields = ('name', 'image', 'text')

    def __init__(self, **kwargs):
        self.user = kwargs.pop('user')

        super().__init__(**kwargs)

        self.tune_fields()

    def tune_fields(self):
        self.tune_name_field()
        self.tune_text_field()

    def tune_name_field(self):
        self.fields['name'].widget.attrs.update({'class': 'input'})

    def tune_text_field(self):
        self.fields['text'].widget.attrs.update({'class': 'textarea'})

    def save(self, commit=True):
        if self.instance._state.adding:
            self.instance.author = self.user

        return super().save(commit)

zhmach/apps/accounts/views/login.py
from django.contrib.auth.views import LoginView as DjangoLoginView

from zhmach.apps.accounts.forms import AuthenticationForm


class LoginView(DjangoLoginView):
    template_name = 'accounts/login.html'

    form_class = AuthenticationForm

zhmach/apps/accounts/templates/accounts/login.html
{% extends "main.html" %}

{% block header %}{% endblock header %}
{% block content %}
  <section class="section">
    <form action="{{ form_action }}" method="post">
      {% csrf_token %}

      <h1 class="title">{{ form_title }}</h1>

      {% for field in form %}
        <div class="field">
          <div class="label">{{ field.label_tag }}</div>
          <div class="control">{{ field }}</div>
          <div class="help is-danger">{{ field.errors }}</div>
        </div>
      {% endfor %}

      <div class="help is-danger">
        {{ form.non_field_errors }}
      </div>

      <div class="field is-grouped">
        <div class="control">
          <input type="submit" value="Войти" class="button is-warning"/>
        </div>
      </div>

    </form>
  </section>
{% endblock content %}
{% block footer %}{% endblock footer %}

zhmach/apps/blogs/templates/blogs/create-update.html
{% extends "main.html" %}

{% block content %}
  <section class="section">
    <form action="{{ form_action }}" method="post" enctype="multipart/form-data">
      {% csrf_token %}

      <h1 class="title">{{ form_title }}</h1>

      {% for field in form %}
        <div class="field">
          <div class="label">{{ field.label_tag }}</div>
          <div class="control">{{ field }}</div>
          <div class="help is-danger">{{ field.errors }}</div>
        </div>
      {% endfor %}

      <div class="help is-danger">
        {{ form.non_field_errors }}
      </div>

      <div class="field is-grouped">
        <div class="control">
          <input type="submit" value="Сохранить" class="button is-warning"/>
        </div>
        <div class="control">
          <a class="button is-text"
             href="javascript:history.back()">Отменить</a>
        </div>
      </div>

    </form>
  </section>
{% endblock content %}

zhmach/apps/blogs/templates/blogs/create.html
{% extends "main.html" %}

{% block content %}
  <form class="form-horizontal" action="{{ form_action }}" method="post">
    {% csrf_token %}

    <legend>Add blog</legend>

    <div class="field">
      <div class="help is-danger">{{ form.name.errors }}</div>
      <div class="label">{{ form.name.label_tag }}</div>
      <div class="control">{{ form.name }}</div>
    </div>

    <div class="field">
      <div class="label">{{ form.text.label_tag }}</div>
      <div class="control">{{ form.text }}</div>
      <div class="help is-danger">{{ form.text.errors }}</div>
    </div>

   <div class="field">
     <div class="control">
       <input type="submit" class="button is-primary"/>
     </div>
   </div>
  </form>
{% endblock content %}

zhmach/apps/blogs/templates/blogs/detail.html
{% extends "main.html" %}

{% block content %}
  <section class="section">
    <h1 class="title">{{ object }}</h1>
    <h2 class="is-size-7">
      <span>{{ object.author }} | {{ object.created_at }}</span>
    </h2>
    {% if user.is_authenticated %}
      <div class="buttons has-margin-top">
        <a class="button is-warning" href="{{ object.get_update_url }}">
          <strong>Редактировать</strong>
        </a>
        <form method="post" action="{{ object.get_delete_url }}">
           {% csrf_token %}
          <input class="button is-danger" type="submit" value="Удалить">
        </form>
      </div>
    {% endif %}
    {% if object.image %}
      <figure class="image is-4by3 has-margin-top">
        <img src="{{ object.image.url }}">
      </figure>
    {% endif %}
    <p class="content has-margin-top">{{ object.text|linebreaksbr }}</p>
  </section>
{% endblock content %}

zhmach/apps/blogs/templates/blogs/list.html
{% extends "main.html" %}

{% load static %}

{% block content %}
  {% for object in object_list %}
    <section class="section">
      <h1 class="title">
        <a href="{{ object.get_absolute_url }}" class="has-text-grey-darker">
          {{ object }}
        </a>
      </h1>
      <div class="columns">
        <div class="column">
          <h2 class="is-size-7">
            <span>{{ object.author }} | {{ object.created_at }}</span>
          </h2>
        </div>
        <div class="column">
          <h2 class="is-size-7 has-text-right">
            <span>
              <img width="10px" height="10px" src="{% static "eye.svg" %}"/>&nbsp;{{ object.views }}
            </span>
          </h2>
        </div>
      </div>
      {% if object.image %}
        <figure class="image is-4by3 has-margin-top">
          <img src="{{ object.image.url }}">
        </figure>
      {% endif %}
      <p class="content has-margin-top">{{ object.text|linebreaksbr|truncatewords:50 }}</p>
    </section>
  {% endfor %}
{% endblock content %}

zhmach/templates/helpers/_footer.html
<footer class="footer has-background-white-ter">
  <div class="content has-text-centered">
    <p><strong>Дарья Жмаченко</strong></p>
    <p>&copy; 2018</p>
  </div>
</footer>

zhmach/templates/helpers/_header.html
<nav class="navbar is-fixed-top is-dark">
  <div class="navbar-brand">
    <div class="navbar-item has-text-brand is-size-4">
      Z
    </div>
  </div>
  <div class="navbar-menu">
    <div class="navbar-start">
      <a class="navbar-item" href="{% url "blogs:blog-list" %}">Статьи</a>
    </div>
    <div class="navbar-end">
      <div class="navbar-item">
        <div class="buttons">
          {% if user.is_authenticated %}
            <a class="button is-warning" href="{% url "blogs:blog-create" %}">
              <strong>Добавить статью</strong>
            </a>
            <a class="button is-light" href="{% url "logout" %}">
              Выйти
            </a>
          {% else %}
          <a class="button is-light" href="{% url "login" %}">
            Войти
          </a>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
</nav>

zhmach/templates/main.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Статьи-статейки</title>
  <link rel="stylesheet" href="{% static "bulma.min.css" %}">
  <link rel="stylesheet" href="{% static "all.min.css" %}">
  <link rel="icon" type="image/x-icon" href="{% static "favicon.ico" %}" />

  <style>
    body {
      display: flex;
      min-height: 100vh;
      flex-direction: column;
    }

    #wrapper {
      flex: 1 0 auto;
    }

    .has-text-brand {
      font-family: 'Covered By Your Grace', cursive;
    }
    .has-margin-top {
      margin-top: 1rem;
    }
  </style>
</head>
<body class="has-navbar-fixed-top has-background-white-ter">
  {% block body %}
    {% block header %}
      {% include "helpers/_header.html" %}
    {% endblock header %}
    <div id="wrapper">
      <div class="columns is-centered has-background-white">
        <div class="column is-one-third">
          {% block content %}
          {% endblock content %}
        </div>
      </div>
    </div>
    {% block footer %}
      {% include "helpers/_footer.html" %}
    {% endblock footer %}
  {% endblock body %}
</body>
</html>